feat(gha): Add new gha for test for voice with postgres instance creation
OpenPhone/gha pull request #36
Opened 2023-04-18 20:02 UTC by mikepatt38

Create a GHA workflow that will work with the new voice db

2023-04-18 20:17 UTC, Wagan8r commented on .github/workflows/test-integration-postgres-redis-rabbit.yml
> +name: Reusable workflow for running postgres (with prisma) with rabbit and redis integration tests
```suggestion
name: Reusable workflow for running postgres, rabbit, and redis integration tests
```
There's nothing "Prisma" about this workflow.

2023-04-18 20:20 UTC, Wagan8r requested changes
This whole workflow should be largely a copy/paste of the existing postgres workflows, including all of the `postgres_xyz` related and `setup_global_postgres`, `migration_command`, etc. inputs.

2023-04-18 20:56 UTC, Wagan8r commented on .github/workflows/test-integration-postgres-redis-rabbit.yml
> +      global_postgres_ref:
I'd probably just remove this.

2023-04-18 20:57 UTC, Wagan8r commented on .github/workflows/test-integration-postgres-redis-rabbit.yml
> +        type: string
```suggestion
```
This is in here twice

2023-04-18 20:59 UTC, Wagan8r reviewed
This looks good, but waiting to approve until you test it. You can reference it in `voice` via:
```
  test-integration:
    uses: OpenPhone/gha/.github/workflows/test-integration-rabbit-redis.yml@ENG-7464
```
Once this is merged, you'll want to make a PR from `main` -> `v3`

2023-04-19 14:46 UTC, bmatcuk approved these changes
Works in my [repository pr](https://github.com/OpenPhone/voice/pull/711)

2023-04-19 14:56 UTC, thesmo approved these changes

2023-04-19 14:56 UTC, Wagan8r approved these changes

2023-04-19 15:00 UTC, merged